server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://47.115.201.168:3306/data?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: bx172819.

file:
  save-path: D:\clp-data\upload\bulletin\
  json-url: 116.62.190.1:9999
  csv:
    save-path: D:\clp-data\upload\csv\
  result:
    save-path: D:\clp-data\upload\temp-task-result\

  template:
    word:
      save-path: D:\clp-data\upload\template-word\
    html:
      save-path: D:\clp-data\upload\template-html\
  image:
      save-path: D:\clp-data\upload\image\
debug: true
