
server:
  port: 9123

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/heimao?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: 12345678

file:
  csv:
    save-path: /home/mjy/project/heimao-back/file/csv/
  result:
    save-path: /home/mjy/project/heimao-back/file/temp-task-result/
  save-path: /home/mjy/project/heimao-back/file/bulletin/
  json-url: 116.62.190.1:9999
  template:
    word:
      save-path: /home/mjy/project/heimao-back/file/template-word/
    html:
      save-path: /home/mjy/project/heimao-back/file/template-html/
  image:
      save-path: /home/mjy/project/heimao-back/file/image/
debug: true
